layout_spectrum: 0.4743481073528528
typography_spectrum: 0.2663416378200054
color:
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  brandStrength: 0.00459107244387269
  lightness: 0.6080722757615149
  saturation: 0.372538932133466
  rhythmicContrast: 0.8484982342924923
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: drmobius
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Hi
description: Sup.
purpose: []
